import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "./providers/query-provider";
import { Toaster } from "@/components/ui/sonner";
import { QuizProvider } from "./providers/context-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Quiz Builder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-slate-100 antialiased`}
      >
        <QueryProvider>
          <QuizProvider>
            <div className="min-h-screen flex items-center justify-center">
              {children}
            </div>
          </QuizProvider>
        </QueryProvider>
        <Toaster richColors />
      </body>
    </html>
  );
}
